---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: akregistry2109.azurecr.io/anupkalita/azure-devops-task:latest
        name: apache
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - port: 80
  selector:
    app: apache
